name = "raw2"
type = "javascript"
# zone_id = ""
account_id = ""
# route = ""
workers_dev = true
compatibility_date = "2022-02-26"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
[[kv_namespaces]]
binding = "DATA"
preview_id = ""
id = ""
[vars]
ORIGINS = "*"
METHODS = "GET, OPTIONS"
[dev]
port = 8585